In [2]:
import pandas as pd

In [4]:
df=pd.read_csv("C:/Users/kamal/OneDrive/Desktop/Data Analytic project/Zomato-Banglore-Market-Analysis/1.dataset/1.Raw data/zomato.csv" )

In [3]:
df.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [4]:
df.shape

(51717, 17)

In [5]:
df.columns

Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='str')

In [6]:
df.dtypes

url                              str
address                          str
name                             str
online_order                     str
book_table                       str
rate                             str
votes                          int64
phone                            str
location                         str
rest_type                        str
dish_liked                       str
cuisines                         str
approx_cost(for two people)      str
reviews_list                     str
menu_item                        str
listed_in(type)                  str
listed_in(city)                  str
dtype: object

In [7]:
df["rate"].head(10)

0    4.1/5
1    4.1/5
2    3.8/5
3    3.7/5
4    3.8/5
5    3.8/5
6    3.6/5
7    4.6/5
8    4.0/5
9    4.2/5
Name: rate, dtype: str

In [8]:
df["rate"].unique()

<StringArray>
[ '4.1/5',  '3.8/5',  '3.7/5',  '3.6/5',  '4.6/5',  '4.0/5',  '4.2/5',
  '3.9/5',  '3.1/5',  '3.0/5',  '3.2/5',  '3.3/5',  '2.8/5',  '4.4/5',
  '4.3/5',    'NEW',  '2.9/5',  '3.5/5',      nan,  '2.6/5', '3.8 /5',
  '3.4/5',  '4.5/5',  '2.5/5',  '2.7/5',  '4.7/5',  '2.4/5',  '2.2/5',
  '2.3/5', '3.4 /5',      '-', '3.6 /5',  '4.8/5', '3.9 /5', '4.2 /5',
 '4.0 /5', '4.1 /5', '3.7 /5', '3.1 /5', '2.9 /5', '3.3 /5', '2.8 /5',
 '3.5 /5', '2.7 /5', '2.5 /5', '3.2 /5', '2.6 /5', '4.5 /5', '4.3 /5',
 '4.4 /5',  '4.9/5',  '2.1/5',  '2.0/5',  '1.8/5', '4.6 /5', '4.9 /5',
 '3.0 /5', '4.8 /5', '2.3 /5', '4.7 /5', '2.4 /5', '2.1 /5', '2.2 /5',
 '2.0 /5', '1.8 /5']
Length: 65, dtype: str

In [9]:
df["rate"].value_counts()

rate
NEW       2208
3.9/5     2098
3.8/5     2022
3.7/5     2011
3.9 /5    1874
          ...
2.2 /5       7
2.0 /5       7
2.0/5        4
1.8 /5       3
1.8/5        2
Name: count, Length: 64, dtype: int64

In [10]:
df["rate"].isna().sum()

np.int64(7775)

In [11]:
(df["rate"]=='-').sum()

np.int64(69)

In [12]:
(10052 / len(df)) * 100

19.436548910416303

In [13]:
df.isna().sum()

url                                0
address                            0
name                               0
online_order                       0
book_table                         0
rate                            7775
votes                              0
phone                           1208
location                          21
rest_type                        227
dish_liked                     28078
cuisines                          45
approx_cost(for two people)      346
reviews_list                       0
menu_item                          0
listed_in(type)                    0
listed_in(city)                    0
dtype: int64

In [14]:
df["rate"].str.replace("/5","")

0         4.1
1         4.1
2         3.8
3         3.7
4         3.8
         ...
51712    3.6
51713     NaN
51714     NaN
51715    4.3
51716    3.4
Name: rate, Length: 51717, dtype: str

In [15]:
df["rate"].str.replace("/5","").head(10)

0    4.1
1    4.1
2    3.8
3    3.7
4    3.8
5    3.8
6    3.6
7    4.6
8    4.0
9    4.2
Name: rate, dtype: str

In [16]:
df["rate"].str.replace("/5","").str.strip().head(10)

0    4.1
1    4.1
2    3.8
3    3.7
4    3.8
5    3.8
6    3.6
7    4.6
8    4.0
9    4.2
Name: rate, dtype: str

In [17]:
df["rate"].replace(["NEW", "-"], pd.NA).isna().sum()

np.int64(10052)

In [18]:
pd.to_numeric(
    df["rate"].str.replace("/5", "").str.strip(),
    errors="coerce"
).head(10)

0    4.1
1    4.1
2    3.8
3    3.7
4    3.8
5    3.8
6    3.6
7    4.6
8    4.0
9    4.2
Name: rate, dtype: float64

In [52]:
df["cleaned_ratings"] =pd.to_numeric(
    df["rate"].str.replace("/5", "").str.strip(),
    errors="coerce")

In [20]:
df["cleaned_ratings"].isna().sum()

np.int64(10052)

In [4]:
df["approx_cost(for two people)"].head(10)

0    800
1    800
2    800
3    300
4    600
5    600
6    800
7    600
8    700
9    550
Name: approx_cost(for two people), dtype: str

In [5]:
df["approx_cost(for two people)"].unique()

<StringArray>
[  '800',   '300',   '600',   '700',   '550',   '500',   '450',   '650',
   '400',   '900',   '200',   '750',   '150',   '850',   '100', '1,200',
   '350',   '250',   '950', '1,000', '1,500', '1,300',   '199',    '80',
 '1,100',   '160', '1,600',   '230',   '130',    '50',   '190', '1,700',
     nan, '1,400',   '180', '1,350', '2,200', '2,000', '1,800', '1,900',
   '330', '2,500', '2,100', '3,000', '2,800', '3,400',    '40', '1,250',
 '3,500', '4,000', '2,400', '2,600',   '120', '1,450',   '469',    '70',
 '3,200',    '60',   '560',   '240',   '360', '6,000', '1,050', '2,300',
 '4,100', '5,000', '3,700', '1,650', '2,700', '4,500',   '140']
Length: 71, dtype: str

In [6]:
df["approx_cost(for two people)"].isna().sum()

np.int64(346)

In [7]:
df["approx_cost(for two people)"].value_counts()

approx_cost(for two people)
300      7576
400      6562
500      4980
200      4857
600      3714
         ...
469         1
60          1
560         1
5,000       1
3,700       1
Name: count, Length: 70, dtype: int64

In [9]:
df["approx_cost(for two people)"].dtypes

In [10]:
df["approx_cost(for two people)"].str.replace(",","").head(10)

0    800
1    800
2    800
3    300
4    600
5    600
6    800
7    600
8    700
9    550
Name: approx_cost(for two people), dtype: str

In [49]:
df["cleaned_cost"]=pd.to_numeric( df["approx_cost(for two people)"].str.replace(",",""), errors="coerce")

In [13]:
df["cleaned_cost"].isna().sum()

np.int64(346)

In [14]:
df["cleaned_cost"].dtypes

dtype('float64')

### find top 10 most frequent location

In [15]:
df["location"].value_counts().head(10)

location
BTM                      5124
HSR                      2523
Koramangala 5th Block    2504
JP Nagar                 2235
Whitefield               2144
Indiranagar              2083
Jayanagar                1926
Marathahalli             1846
Bannerghatta Road        1630
Bellandur                1286
Name: count, dtype: int64

In [16]:
df["location"].isna().sum()

np.int64(21)

In [17]:
df["location"].unique()

<StringArray>
[                 'Banashankari',                  'Basavanagudi',
                   'Mysore Road',                     'Jayanagar',
            'Kumaraswamy Layout',          'Rajarajeshwari Nagar',
                   'Vijay Nagar',                   'Uttarahalli',
                      'JP Nagar',               'South Bangalore',
                   'City Market',                    'Nagarbhavi',
             'Bannerghatta Road',                           'BTM',
               'Kanakapura Road',                  'Bommanahalli',
                             nan,                'CV Raman Nagar',
               'Electronic City',                           'HSR',
                  'Marathahalli',                 'Sarjapur Road',
                 'Wilson Garden',                  'Shanti Nagar',
         'Koramangala 5th Block',         'Koramangala 8th Block',
                 'Richmond Road',         'Koramangala 7th Block',
                     'Jalahalli',         'Koramangala 4th Block',
                     'Bellandur',                    'Whitefield',
                'East Bangalore',              'Old Airport Road',
                   'Indiranagar',         'Koramangala 1st Block',
                   'Frazer Town',                      'RT Nagar',
                       'MG Road',                  'Brigade Road',
                  'Lavelle Road',                 'Church Street',
                        'Ulsoor',                'Residency Road',
                  'Shivajinagar',                 'Infantry Road',
                'St. Marks Road',               'Cunningham Road',
              'Race Course Road',             'Commercial Street',
                 'Vasanth Nagar',                    'HBR Layout',
                        'Domlur',                       'Ejipura',
            'Jeevan Bhima Nagar',               'Old Madras Road',
                  'Malleshwaram',                 'Seshadripuram',
                  'Kammanahalli',         'Koramangala 6th Block',
                      'Majestic',                 'Langford Town',
             'Central Bangalore',                  'Sanjay Nagar',
                   'Brookefield',    'ITPL Main Road, Whitefield',
 'Varthur Main Road, Whitefield',                      'KR Puram',
         'Koramangala 2nd Block',         'Koramangala 3rd Block',
                   'Koramangala',                    'Hosur Road',
                   'Rajajinagar',                     'Banaswadi',
               'North Bangalore',                      'Nagawara',
                        'Hennur',                  'Kalyan Nagar',
                  'New BEL Road',                        'Jakkur',
               'Rammurthy Nagar',                  'Thippasandra',
                 'Kaggadasapura',                        'Hebbal',
                       'Kengeri',                   'Sankey Road',
                'Sadashiv Nagar',            'Basaveshwara Nagar',
                   'Yeshwantpur',                'West Bangalore',
                   'Magadi Road',                     'Yelahanka',
                'Sahakara Nagar',                        'Peenya']
Length: 94, dtype: str

In [18]:
df["location"].str.strip()

0                      Banashankari
1                      Banashankari
2                      Banashankari
3                      Banashankari
4                      Basavanagudi
                    ...
51712                    Whitefield
51713                    Whitefield
51714                    Whitefield
51715    ITPL Main Road, Whitefield
51716    ITPL Main Road, Whitefield
Name: location, Length: 51717, dtype: str

In [45]:
df["cleaned_location"] = df["location"].str.strip()

In [21]:
df["cuisines"].head(10)

0                 North Indian, Mughlai, Chinese
1                    Chinese, North Indian, Thai
2                         Cafe, Mexican, Italian
3                     South Indian, North Indian
4                       North Indian, Rajasthani
5                                   North Indian
6    North Indian, South Indian, Andhra, Chinese
7                           Pizza, Cafe, Italian
8                     Cafe, Italian, Continental
9       Cafe, Mexican, Italian, Momos, Beverages
Name: cuisines, dtype: str

In [22]:
df["cuisines"].isna().sum()

np.int64(45)

In [23]:
df["cuisines"].str.strip()

0                North Indian, Mughlai, Chinese
1                   Chinese, North Indian, Thai
2                        Cafe, Mexican, Italian
3                    South Indian, North Indian
4                      North Indian, Rajasthani
                          ...
51712                               Continental
51713                               Finger Food
51714                               Finger Food
51715                               Finger Food
51716    Finger Food, North Indian, Continental
Name: cuisines, Length: 51717, dtype: str

In [50]:
df["cleaned_cuisines"]=df["cuisines"].str.strip()

In [25]:
df["cleaned_cuisines"].isna().sum()

np.int64(45)

In [3]:
df["rest_type"].value_counts()

rest_type
Quick Bites                   19132
Casual Dining                 10330
Cafe                           3732
Delivery                       2604
Dessert Parlor                 2263
                              ...
Pop Up                            2
Food Court, Beverage Shop         2
Dessert Parlor, Food Court        2
Sweet Shop, Dessert Parlor        1
Quick Bites, Kiosk                1
Name: count, Length: 93, dtype: int64

In [4]:
df["rest_type"].isna().sum()

np.int64(227)

In [5]:
df["rest_type"].unique()

<StringArray>
[                'Casual Dining',           'Cafe, Casual Dining',
                   'Quick Bites',           'Casual Dining, Cafe',
                          'Cafe',             'Quick Bites, Cafe',
             'Cafe, Quick Bites',                      'Delivery',
                          'Mess',                'Dessert Parlor',
        'Bakery, Dessert Parlor',                           'Pub',
                        'Bakery',            'Takeaway, Delivery',
                   'Fine Dining',                 'Beverage Shop',
                    'Sweet Shop',                           'Bar',
    'Beverage Shop, Quick Bites',                 'Confectionery',
    'Quick Bites, Beverage Shop',    'Dessert Parlor, Sweet Shop',
           'Bakery, Quick Bites',       'Sweet Shop, Quick Bites',
                         'Kiosk',                    'Food Truck',
   'Quick Bites, Dessert Parlor', 'Beverage Shop, Dessert Parlor',
                      'Takeaway',            'Pub, Casual Dining',
            'Casual Dining, Bar', 'Dessert Parlor, Beverage Shop',
           'Quick Bites, Bakery',   'Dessert Parlor, Quick Bites',
   'Microbrewery, Casual Dining',                        'Lounge',
            'Bar, Casual Dining',                    'Food Court',
                  'Cafe, Bakery',                             nan,
                         'Dhaba',       'Quick Bites, Sweet Shop',
                  'Microbrewery',       'Food Court, Quick Bites',
                      'Pub, Bar',            'Casual Dining, Pub',
                   'Lounge, Bar',    'Food Court, Dessert Parlor',
     'Casual Dining, Sweet Shop',     'Food Court, Casual Dining',
   'Casual Dining, Microbrewery',    'Sweet Shop, Dessert Parlor',
         'Bakery, Beverage Shop',         'Lounge, Casual Dining',
              'Cafe, Food Court',           'Beverage Shop, Cafe',
          'Cafe, Dessert Parlor',          'Dessert Parlor, Cafe',
        'Dessert Parlor, Bakery',             'Microbrewery, Pub',
            'Bakery, Food Court',                          'Club',
       'Quick Bites, Food Court',                  'Bakery, Cafe',
                     'Bar, Cafe',                     'Pub, Cafe',
    'Casual Dining, Irani Cafee',           'Fine Dining, Lounge',
              'Bar, Quick Bites',                 'Bakery, Kiosk',
             'Pub, Microbrewery',          'Microbrewery, Lounge',
     'Fine Dining, Microbrewery',              'Fine Dining, Bar',
             'Mess, Quick Bites',         'Dessert Parlor, Kiosk',
                    'Bhojanalya',    'Casual Dining, Quick Bites',
                        'Pop Up',                     'Cafe, Bar',
         'Casual Dining, Lounge',            'Bakery, Sweet Shop',
             'Microbrewery, Bar',                  'Cafe, Lounge',
                      'Bar, Pub',                  'Lounge, Cafe',
           'Club, Casual Dining',             'Quick Bites, Mess',
        'Quick Bites, Meat Shop',            'Quick Bites, Kiosk',
          'Lounge, Microbrewery',     'Food Court, Beverage Shop',
    'Dessert Parlor, Food Court',                   'Bar, Lounge']
Length: 94, dtype: str

In [15]:
df["cleaned_rest_type"] = df["rest_type"].str.strip()

In [16]:
rest_type_df = df.copy()

In [17]:
rest_type_df["cleaned_rest_type"] = (
    rest_type_df["cleaned_rest_type"].str.split(",")
)

In [18]:
rest_type_df = rest_type_df.explode("cleaned_rest_type")

In [19]:
rest_type_df["cleaned_rest_type"] = (
    rest_type_df["cleaned_rest_type"].str.strip()
)

In [20]:
rest_type_df["cleaned_rest_type"].value_counts().head(10)

cleaned_rest_type
Quick Bites       20639
Casual Dining     13057
Cafe               5074
Delivery           4641
Dessert Parlor     3211
Bar                2457
Takeaway           2157
Bakery             1998
Beverage Shop      1471
Pub                 950
Name: count, dtype: int64

In [21]:
(rest_type_df["cleaned_rest_type"] == "").sum()

np.int64(0)

In [22]:
rest_type_df["cleaned_rest_type"].head(10)

0    Casual Dining
1    Casual Dining
2             Cafe
2    Casual Dining
3      Quick Bites
4    Casual Dining
5    Casual Dining
6    Casual Dining
7    Casual Dining
7             Cafe
Name: cleaned_rest_type, dtype: str

In [23]:
df["online_order"].isna().sum()

np.int64(0)

In [24]:
df["online_order"].unique()

<StringArray>
['Yes', 'No']
Length: 2, dtype: str

In [25]:
df["online_order"].value_counts()

online_order
Yes    30444
No     21273
Name: count, dtype: int64

In [26]:
df["book_table"].isna().sum()

np.int64(0)

In [27]:
df["book_table"].unique()

<StringArray>
['Yes', 'No']
Length: 2, dtype: str

In [ ]:
df["book_table"].

In [28]:
df["book_table"].value_counts()

book_table
No     45268
Yes     6449
Name: count, dtype: int64

In [29]:
df["votes"].describe()

count    51717.000000
mean       283.697527
std        803.838853
min          0.000000
25%          7.000000
50%         41.000000
75%        198.000000
max      16832.000000
Name: votes, dtype: float64

In [30]:
df["votes"].isna().sum()

np.int64(0)

In [33]:
 (df["votes"]<0).sum()

np.int64(0)

In [34]:
df["name"].isna().sum()

np.int64(0)

In [36]:
df["name"].str.strip()

0                                                    Jalsa
1                                           Spice Elephant
2                                          San Churro Cafe
3                                    Addhuri Udupi Bhojana
4                                            Grand Village
                               ...
51712    Best Brews - Four Points by Sheraton Bengaluru...
51713                             Vinod Bar And Restaurant
51714    Plunge - Sheraton Grand Bengaluru Whitefield H...
51715    Chime - Sheraton Grand Bengaluru Whitefield Ho...
51716                         The Nest - The Den Bengaluru
Name: name, Length: 51717, dtype: str

In [37]:
df["cleaned_name"]=df["name"].str.strip()

In [38]:
df["cleaned_name"].isna().sum()

np.int64(0)

In [39]:
df.duplicated().sum()

np.int64(0)

In [47]:
df.duplicated(subset=["cleaned_name", "cleaned_location"]).sum()

np.int64(39566)

In [53]:
df.columns.tolist()

['url',
 'address',
 'name',
 'online_order',
 'book_table',
 'rate',
 'votes',
 'phone',
 'location',
 'rest_type',
 'dish_liked',
 'cuisines',
 'approx_cost(for two people)',
 'reviews_list',
 'menu_item',
 'listed_in(type)',
 'listed_in(city)',
 'cleaned_rest_type',
 'cleaned_name',
 'cleaned_location',
 'cleaned_cost',
 'cleaned_cuisines',
 'cleaned_ratings']

In [48]:
df[df.duplicated(
    subset=["cleaned_name", "cleaned_location"],
    keep=False
)][["cleaned_name", "cleaned_location", "listed_in(type)", "rate", "votes"]].head(10)

,cleaned_name,cleaned_location,listed_in(type),rate,votes
0,Jalsa,Banashankari,Buffet,4.1/5,775
1,Spice Elephant,Banashankari,Buffet,4.1/5,787
2,San Churro Cafe,Banashankari,Buffet,3.8/5,918
3,Addhuri Udupi Bhojana,Banashankari,Buffet,3.7/5,88
4,Grand Village,Basavanagudi,Buffet,3.8/5,166
5,Timepass Dinner,Basavanagudi,Buffet,3.8/5,286
6,Rosewood International Hotel - Bar & Restaurant,Mysore Road,Buffet,3.6/5,8
7,Onesta,Banashankari,Cafes,4.6/5,2556
8,Penthouse Cafe,Banashankari,Cafes,4.0/5,324
9,Smacznego,Banashankari,Cafes,4.2/5,504

In [54]:
df.to_csv("zomato_cleaned.csv", index=False)

In [55]:
import os

print(os.path.exists("zomato_cleaned.csv"))

True

In [56]:
import os
print(os.path.abspath("zomato_cleaned.csv"))

C:\Users\kamal\zomato_cleaned.csv

In [63]:
df.to_csv(
    r"C:/Users/kamal/OneDrive/Desktop/Data Analytic project/Zomato-Banglore-Market-Analysis/1.dataset/2.Processed Data/zomato_cleaned.csv",
    index=False
)

In [64]:
sql_columns = [
    "cleaned_name",
    "cleaned_location",
    "cleaned_ratings",
    "votes",
    "cleaned_cost",
    "cleaned_cuisines",
    "cleaned_rest_type",
    "online_order",
    "book_table",
    "listed_in(type)",
    "listed_in(city)"
]

sql_df = df[sql_columns].copy()

In [65]:
sql_df.to_csv(
    r"C:/Users/kamal/OneDrive/Desktop/Data Analytic project/Zomato-Banglore-Market-Analysis/1.dataset/2.Processed Data/zomato_sql_ready.csv",
    index=False,
    encoding="utf-8-sig"
)

In [1]:
import pandas as pd

df = pd.read_csv("zomato_sql_ready.csv")

print(df["cleaned_ratings"].dtype)
print(df["cleaned_ratings"].isna().sum())
print(df["cleaned_ratings"].head(10))

FileNotFoundError: [Errno 2] No such file or directory: 'zomato_sql_ready.csv'

In [2]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\kamal\OneDrive\Desktop\Data Analytic project\Zomato-Banglore-Market-Analysis\1.dataset\2.Processed Data\zomato_sql_ready.csv"
)

print(df["cleaned_ratings"].dtype)
print(df["cleaned_ratings"].isna().sum())
print(df["cleaned_ratings"].head(10))

float64
10052
0    4.1
1    4.1
2    3.8
3    3.7
4    3.8
5    3.8
6    3.6
7    4.6
8    4.0
9    4.2
Name: cleaned_ratings, dtype: float64

In [3]:
print(df["cleaned_ratings"].dtype)
print(df["cleaned_ratings"].isna().sum())
print(df["cleaned_ratings"].head(10))

float64
10052
0    4.1
1    4.1
2    3.8
3    3.7
4    3.8
5    3.8
6    3.6
7    4.6
8    4.0
9    4.2
Name: cleaned_ratings, dtype: float64

In [4]:

df.to_csv(
    "zomato_mysql_ready.csv",
    index=False,
    encoding="utf-8-sig",
    na_rep="\\N"
)

In [5]:
import os
print(os.path.abspath("zomato_mysql_ready.csv"))

C:\Users\kamal\zomato_mysql_ready.csv

In [5]:
print(df["cleaned_ratings"].isna().sum())
print(df["cleaned_ratings"].value_counts(dropna=False).head(10))

KeyError: 'cleaned_ratings'

In [6]:
print(df.columns.tolist())

['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes', 'phone', 'location', 'rest_type', 'dish_liked', 'cuisines', 'approx_cost(for two people)', 'reviews_list', 'menu_item', 'listed_in(type)', 'listed_in(city)']

In [7]:
import pandas as pd

df_clean = pd.read_csv("zomato_sql_ready.csv")

print(df_clean.shape)
print(df_clean.columns.tolist())

FileNotFoundError: [Errno 2] No such file or directory: 'zomato_sql_ready.csv'

In [8]:
import os

print(os.getcwd())
print(os.listdir())

C:\Users\kamal
['.config', '.idlerc', '.ipynb_checkpoints', '.ipython', '.jupyter', '.matplotlib', '.python_history', '.vscode', 'AppData', 'Application Data', 'Contacts', 'Cookies', 'Data Analysis-EDA-Project-e.ipynb', 'Data cleaning.ipynb', 'data.csv', 'Downloads', 'Favorites', 'first-react-app', 'HR Attrition EDA .ipynb', 'IntelGraphicsProfiles', 'Local Settings', 'Music', 'My Documents', 'NetHood', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{b644cf9e-4efc-11f0-bf45-97cdde797372}.TM.blf', 'NTUSER.DAT{b644cf9e-4efc-11f0-bf45-97cdde797372}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{b644cf9e-4efc-11f0-bf45-97cdde797372}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'Numpy learning', 'numpy practise', 'OneDrive', 'Pandas practise.txt', 'Pnadas learning', 'PrintHood', 'python', 'PYTHON LEARNING', 'Recent', 'Saved Games', 'Searches', 'second-react-app', 'SendTo', 'source', 'Start Menu', 'student.csv', 'Templates', 'Untitled.ipynb', 'untitled.py', 'untitled.txt', 'Untitled1.ipynb', 'untitled1.py', 'untitled1.txt', 'Untitled10.ipynb', 'Untitled11.ipynb', 'Untitled12.ipynb', 'Untitled2.ipynb', 'untitled2.txt', 'Untitled3.ipynb', 'untitled3.txt', 'Untitled4.ipynb', 'untitled4.txt', 'Untitled5.ipynb', 'Untitled6.ipynb', 'Untitled7.ipynb', 'Untitled8.ipynb', 'Untitled9.ipynb', 'Videos', 'zomato_cleaned.csv', 'zomato_mysql_ready.csv']

In [9]:
import pandas as pd

df_clean = pd.read_csv("zomato_mysql_ready.csv")

print(df_clean.shape)
print(df_clean.columns.tolist())

(51717, 17)
['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes', 'phone', 'location', 'rest_type', 'dish_liked', 'cuisines', 'approx_cost(for two people)', 'reviews_list', 'menu_item', 'listed_in(type)', 'listed_in(city)']

In [10]:
df_clean = pd.read_csv("zomato_cleaned.csv")

print(df_clean.shape)
print(df_clean.columns.tolist())

(51717, 23)
['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes', 'phone', 'location', 'rest_type', 'dish_liked', 'cuisines', 'approx_cost(for two people)', 'reviews_list', 'menu_item', 'listed_in(type)', 'listed_in(city)', 'cleaned_rest_type', 'cleaned_name', 'cleaned_location', 'cleaned_cost', 'cleaned_cuisines', 'cleaned_ratings']

In [11]:
print(df_clean["cleaned_ratings"].isna().sum())
print(df_clean["cleaned_ratings"].value_counts(dropna=False).head(10))

10052
cleaned_ratings
NaN    10052
3.9     3972
3.8     3873
3.7     3821
3.6     3316
4.0     3183
4.1     2948
3.5     2784
3.4     2476
3.3     2310
Name: count, dtype: int64

In [12]:
print(df_clean["cleaned_ratings"].dtype)
print(df_clean["cleaned_cost"].isna().sum())
print(df_clean["cleaned_cost"].dtype)

float64
346
float64

In [13]:
sql_columns = [
    "cleaned_name",
    "cleaned_location",
    "cleaned_ratings",
    "votes",
    "cleaned_cost",
    "cleaned_cuisines",
    "cleaned_rest_type",
    "online_order",
    "book_table",
    "listed_in(type)",
    "listed_in(city)"
]

df_sql = df_clean[sql_columns].copy()

df_sql.to_csv(
    "zomato_final_sql.csv",
    index=False,
    encoding="utf-8",
    na_rep=""
)

print(df_sql.shape)
print("CSV created successfully!")

(51717, 11)
CSV created successfully!

In [14]:
print(df_sql["cleaned_ratings"].isna().sum())
print(df_sql["cleaned_cost"].isna().sum())
print(df_sql["votes"].isna().sum())

10052
346
0

In [15]:
print(
    df_sql[
        df_sql["cleaned_ratings"].isna()
        | df_sql["cleaned_cost"].isna()
    ].shape[0]
)

10299

In [16]:
%pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-26.7.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Downloading mysql_connector_python-26.7.0-cp313-cp313-win_amd64.whl (17.7 MB)
   ---------------------------------------- 0.0/17.7 MB ? eta -:--:--
    --------------------------------------- 0.3/17.7 MB ? eta -:--:--
   - -------------------------------------- 0.8/17.7 MB 2.3 MB/s eta 0:00:08
   -- ------------------------------------- 1.0/17.7 MB 2.3 MB/s eta 0:00:08
   --- ------------------------------------ 1.6/17.7 MB 2.0 MB/s eta 0:00:09
   ---- ----------------------------------- 1.8/17.7 MB 2.1 MB/s eta 0:00:08
   ----- ---------------------------------- 2.4/17.7 MB 2.0 MB/s eta 0:00:08
   ----- ---------------------------------- 2.6/17.7 MB 1.9 MB/s eta 0:00:08
   ------ --------------------------------- 2.9/17.7 MB 1.9 MB/s eta 0:00:08
   ------- -------------------------------- 3.1/17.7 MB 1.9 MB/s eta 0:00:08
   ------- -------------------------------- 3.4/17.7 MB 1.7 MB/s eta 0:00:09
   -------- ------------------------------- 3.7/17.7 MB 1.6 MB/s eta 0:00:09
   -------- ------------------------------- 3.9/17.7 MB 1.6 MB/s eta 0:00:09
   --------- ------------------------------ 4.2/17.7 MB 1.6 MB/s eta 0:00:09
   --------- ------------------------------ 4.2/17.7 MB 1.6 MB/s eta 0:00:09
   ---------- ----------------------------- 4.5/17.7 MB 1.5 MB/s eta 0:00:09
   ---------- ----------------------------- 4.5/17.7 MB 1.5 MB/s eta 0:00:09
   ---------- ----------------------------- 4.7/17.7 MB 1.4 MB/s eta 0:00:10
   ----------- ---------------------------- 5.0/17.7 MB 1.4 MB/s eta 0:00:10
   ------------ --------------------------- 5.5/17.7 MB 1.4 MB/s eta 0:00:09
   ------------- -------------------------- 6.0/17.7 MB 1.4 MB/s eta 0:00:09
   -------------- ------------------------- 6.3/17.7 MB 1.5 MB/s eta 0:00:08
   -------------- ------------------------- 6.6/17.7 MB 1.5 MB/s eta 0:00:08
   --------------- ------------------------ 6.8/17.7 MB 1.5 MB/s eta 0:00:08
   ---------------- ----------------------- 7.1/17.7 MB 1.4 MB/s eta 0:00:08
   ----------------- ---------------------- 7.6/17.7 MB 1.5 MB/s eta 0:00:07
   ------------------ --------------------- 8.1/17.7 MB 1.5 MB/s eta 0:00:07
   ------------------ --------------------- 8.4/17.7 MB 1.5 MB/s eta 0:00:07
   ------------------- -------------------- 8.7/17.7 MB 1.5 MB/s eta 0:00:07
   ------------------- -------------------- 8.7/17.7 MB 1.5 MB/s eta 0:00:07
   -------------------- ------------------- 8.9/17.7 MB 1.4 MB/s eta 0:00:07
   --------------------- ------------------ 9.4/17.7 MB 1.4 MB/s eta 0:00:06
   --------------------- ------------------ 9.4/17.7 MB 1.4 MB/s eta 0:00:06
   ---------------------- ----------------- 10.0/17.7 MB 1.4 MB/s eta 0:00:06
   ----------------------- ---------------- 10.2/17.7 MB 1.4 MB/s eta 0:00:06
   ------------------------ --------------- 10.7/17.7 MB 1.5 MB/s eta 0:00:05
   ------------------------ --------------- 11.0/17.7 MB 1.5 MB/s eta 0:00:05
   ------------------------ --------------- 11.0/17.7 MB 1.5 MB/s eta 0:00:05
   ------------------------- -------------- 11.3/17.7 MB 1.4 MB/s eta 0:00:05
   -------------------------- ------------- 11.5/17.7 MB 1.4 MB/s eta 0:00:05
   -------------------------- ------------- 11.8/17.7 MB 1.4 MB/s eta 0:00:05
   --------------------------- ------------ 12.1/17.7 MB 1.4 MB/s eta 0:00:05
   --------------------------- ------------ 12.1/17.7 MB 1.4 MB/s eta 0:00:05
   --------------------------- ------------ 12.3/17.7 MB 1.4 MB/s eta 0:00:04
   ---------------------------- ----------- 12.6/17.7 MB 1.4 MB/s eta 0:00:04
   ----------------------------- ---------- 12.8/17.7 MB 1.4 MB/s eta 0:00:04
   ----------------------------- ---------- 12.8/17.7 MB 1.4 MB/s eta 0:00:04
   ----------------------------- ---------- 13.1/17.7 MB 1.3 MB/s eta 0:00:04
   ------------------------------ --------- 13.4/17.7 MB 1.3 MB/s eta 0:00:04
   ------------------------------ --------- 13.4/17.7 MB 1.3 MB/s eta 0:00:04
   ------------------------------ --------- 13.6/17.7 MB 1.3 MB/s eta 0:00:04
   ------------------------------ --------- 13.6/17.7 MB 1.3 MB/s eta 0:00:04
   ------------------------------ --------- 13.6/17.7 MB 1.3 MB/s eta 0:00:04
   ------------------------------- -------- 13.9/17.7 MB 1.3 MB/s eta 0:00:03
   -------------------------------- ------- 14.2/17.7 MB 1.3 MB/s eta 0:00:03
   -------------------------------- ------- 14.4/17.7 MB 1.3 MB/s eta 0:00:03
   -------------------------------- ------- 14.4/17.7 MB 1.3 MB/s eta 0:00:03
   --------------------------------- ------ 14.7/17.7 MB 1.2 MB/s eta 0:00:03
   --------------------------------- ------ 14.9/17.7 MB 1.2 MB/s eta 0:00:03
   ---------------------------------- ----- 15.2/17.7 MB 1.2 MB/s eta 0:00:03
   ---------------------------------- ----- 15.5/17.7 MB 1.2 MB/s eta 0:00:02
   ---------------------------------- ----- 15.5/17.7 MB 1.2 MB/s eta 0:00:02
   ----------------------------------- ---- 15.7/17.7 MB 1.2 MB/s eta 0:00:02
   ----------------------------------- ---- 15.7/17.7 MB 1.2 MB/s eta 0:00:02
   ----------------------------------- ---- 15.7/17.7 MB 1.2 MB/s eta 0:00:02
   ------------------------------------ --- 16.0/17.7 MB 1.2 MB/s eta 0:00:02
   ------------------------------------ --- 16.0/17.7 MB 1.2 MB/s eta 0:00:02
   ------------------------------------ --- 16.0/17.7 MB 1.2 MB/s eta 0:00:02
   ------------------------------------ --- 16.3/17.7 MB 1.2 MB/s eta 0:00:02
   ------------------------------------- -- 16.5/17.7 MB 1.1 MB/s eta 0:00:02
   ------------------------------------- -- 16.8/17.7 MB 1.1 MB/s eta 0:00:01
   -------------------------------------- - 17.0/17.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  17.3/17.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------- 17.7/17.7 MB 774.0 kB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-26.7.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import mysql.connector
from getpass import getpass

password = getpass("Enter MySQL password: ")

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password=password,
    database="zomato_market_analysis"
)

print("MySQL connected successfully! ✅")